timeout

diff --git a/.github/workflows/kvssink.yml b/.github/workflows/kvssink.yml
--- a/.github/workflows/kvssink.yml
+++ b/.github/workflows/kvssink.yml
@@ -348,11 +348,25 @@ jobs:
           export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
           export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
           export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
-          gst-launch-1.0 videotestsrc is-live=true num-buffers=450 \
+               
+          set +e  # Disable exit on error for the timeout command
+          timeout --preserve-status --signal=SIGINT --kill-after=15s 30s \
+            gst-launch-1.0 videotestsrc is-live=true num-buffers=450 \
             ! video/x-raw,framerate=30/1,width=640,height=480 \
             ! videoconvert ! x264enc tune=zerolatency key-int-max=45 \
             ! h264parse \
             ! kvssink stream-name='demo-stream-cpp-kvssink-ci-wsl-${{ matrix.image }}'
+          EXIT_CODE=$?
+          set -e  # Re-enable exit on error
+
+          unset AWS_DEFAULT_REGION
+          unset AWS_ACCESS_KEY_ID
+          unset AWS_SECRET_ACCESS_KEY
+          unset AWS_SESSION_TOKEN
+
+          if [[ $EXIT_CODE -ne 0 ]]; then
+            echo "gst-launch-1.0 exited with status: $EXIT_CODE"
+          fi
 
       - name: Verify MKV dump in WSL
         run: |
